services:
  - type: web
    name: outfit-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
    rootDir: backend

  - type: web
    name: outfit-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: frontend/build
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - frontend/**
    rootDir: frontend
